In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('games.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19113 entries, 0 to 19112
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              19113 non-null  object
 1   rated           19113 non-null  bool
 2   turns           19113 non-null  int64
 3   victory_status  19113 non-null  object
 4   winner          19113 non-null  object
 5   increment_code  19113 non-null  object
 6   white_id        19113 non-null  object
 7   white_rating    19113 non-null  int64
 8   black_id        19113 non-null  object
 9   black_rating    19113 non-null  int64
 10  moves           19113 non-null  object
 11  opening_eco     19113 non-null  object
 12  opening_name    19113 non-null  object
 13  opening_ply     19113 non-null  int64
 14  total_time      19113 non-null  float64
 15  initial_time    19113 non-null  int64
 16  increment       19113 non-null  int64
dtypes: bool(1), float64(1), int64(6), object(9)
memory usage: 2.4+ MB

In [17]:
df.head()

,id,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
0,TZJHLljE,False,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5
1,l1NXvwaE,True,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4
2,mIICvQHh,True,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3
3,kWKvrqYL,True,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3
4,9tXo1AUZ,True,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5

In [22]:
df[df['white_id'] == 'nik221107']

,id,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply
4,9tXo1AUZ,True,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5
1390,NdCPoLkf,True,104,mate,black,10+0,nik221107,1526,juncinmestrella,1830,e4 e6 d4 d5 e5 c5 c3 Nc6 Bb5 Qb6 Nf3 Qxb5 Bd2 ...,C02,French Defense: Advance Variation,8

In [12]:
df.drop(columns=['created_at', 'last_move_at'], inplace=True)

In [13]:
#number of duplicate rows
df.duplicated().sum()

516

In [14]:
df.drop_duplicates(inplace=True)

In [16]:
df.shape

(19113, 14)

In [6]:
df.head()

,id,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,total_time,initial_time,increment
0,TZJHLljE,False,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5,15.433333,15,2
1,l1NXvwaE,True,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4,7.666667,5,10
2,mIICvQHh,True,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3,15.166667,5,10
3,kWKvrqYL,True,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3,20.000000,20,0
4,9tXo1AUZ,True,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5,34.750000,30,3

In [29]:
# Extract the numeric part of the increment code and calculate total time
# the first the initial time and the second is the increment per move
# the number of moves is column named 'turns'
# but be careful that the first part is in minutes and the second part is in seconds, so we need to convert the second part to minutes before adding it to the initial time
def calculate_total_time(row):
	initial_time = int(row['increment_code'].split('+')[0])
	increment = int(row['increment_code'].split('+')[1]) / 60  # Convert seconds to minutes
	total_time = initial_time + (increment * row['turns'])  # Assuming an average of 40 moves per game
	return total_time
df['total_time'] = df.apply(calculate_total_time, axis=1)

In [32]:
df['opening_ply'].max()

28

In [33]:
df[df['opening_ply']==df['opening_ply'].max()]

,id,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,total_time
4475,9bIIqx54,False,32,outoftime,black,5+5,ranchowangdu,1500,boseayan,2021,e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 c3 O-O Re...,C89,Ruy Lopez: Marshall Attack | Modern Main Line,28,7.666667
16443,BjplwwJ1,True,34,resign,black,10+0,ramin741,1835,bassem1963,1733,e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O b5 Bb3 Be7 Re...,C89,Ruy Lopez: Marshall Attack | Modern Main Line,28,10.000000
17900,Ms2THNEC,True,45,resign,black,3+8,bratancb,2000,bosspotato,2289,e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb...,C89,Ruy Lopez: Marshall Attack | Modern Main Line,28,9.000000
19412,YaQWFwbu,True,61,resign,white,10+0,balikoevsd,1857,craciun05,1916,e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb...,C89,Ruy Lopez: Marshall Attack | Modern Main Line,28,10.000000

In [5]:
df.to_csv('games.csv', index=False)

In [4]:
df['initial_time'] = df['increment_code'].apply(lambda x: int(x.split('+')[0]))
df['increment'] = df['increment_code'].apply(lambda x: int(x.split('+')[1]))  # Convert seconds to minutes

In [4]:
def classify_game(row):
	initial_minutes = row['initial_time']
	increment_seconds = row['increment']
	if initial_minutes * 60 + increment_seconds * 60 <= 180:
		return 'Bullet'
	elif initial_minutes * 60 + increment_seconds * 60 < 600:
		return 'Blitz'
	elif initial_minutes * 60 + increment_seconds * 60 < 1800:
		return 'Rapid'
	else:
		return 'Classic'

df['type'] = df.apply(classify_game, axis=1)

In [10]:
df.head(10)

,id,rated,turns,victory_status,winner,increment_code,white_id,white_rating,black_id,black_rating,moves,opening_eco,opening_name,opening_ply,total_time,initial_time,increment,type
0,TZJHLljE,False,13,outoftime,white,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,Slav Defense: Exchange Variation,5,15.433333,15,2,Rapid
1,l1NXvwaE,True,16,resign,black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,Nimzowitsch Defense: Kennedy Variation,4,7.666667,5,10,Rapid
2,mIICvQHh,True,61,mate,white,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,King's Pawn Game: Leonardis Variation,3,15.166667,5,10,Rapid
3,kWKvrqYL,True,61,mate,white,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,Queen's Pawn Game: Zukertort Variation,3,20.000000,20,0,Rapid
4,9tXo1AUZ,True,95,mate,white,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,Philidor Defense,5,34.750000,30,3,Classic
5,MsoDV9wj,False,5,draw,draw,10+0,trelynn17,1250,franklin14532,1002,e4 c5 Nf3 Qa5 a3,B27,Sicilian Defense: Mongoose Variation,4,10.000000,10,0,Rapid
6,qwU9rasv,True,33,resign,white,10+0,capa_jr,1520,daniel_likes_chess,1423,d4 d5 e4 dxe4 Nc3 Nf6 f3 exf3 Nxf3 Nc6 Bb5 a6 ...,D00,Blackmar-Diemer Gambit: Pietrowsky Defense,10,10.000000,10,0,Rapid
7,RVN0N3VK,False,9,resign,black,15+30,daniel_likes_chess,1413,soultego,2108,e4 Nc6 d4 e5 d5 Nce7 c3 Ng6 b4,B00,Nimzowitsch Defense: Kennedy Variation | Link...,5,19.500000,15,30,Classic
8,dwF3DJHO,True,66,resign,black,15+0,ehabfanri,1439,daniel_likes_chess,1392,e4 e5 Bc4 Nc6 Nf3 Nd4 d3 Nxf3+ Qxf3 Nf6 h3 Bc5...,C50,Italian Game: Schilling-Kostic Gambit,6,15.000000,15,0,Rapid
9,afoMwnLg,True,119,mate,white,10+0,daniel_likes_chess,1381,mirco25,1209,e4 d5 exd5 Qxd5 Nc3 Qe5+ Be2 Na6 d4 Qf5 Bxa6 b...,B01,Scandinavian Defense: Mieses-Kotroc Variation,4,10.000000,10,0,Rapid